version: '3'
services:
   timescale:
      image: timescale/timescaledb-postgis:latest-pg12
      hostname: timescale
      container_name: timescale
      restart: always
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: postgres
      ports:
         - 5432:5432
      volumes:
         - ./script:/docker-entrypoint-initdb.d/
         - timescale_data:/var/lib/postgresql/data

   adminer:
      image: adminer
      hostname: adminer
      container_name: adminer
      restart: always
      ports:
         - 8080:8080

volumes:
   timescale_data: